name: Portfolio project

on:
  push:
    branches:
      - master

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 5.51.1

    - name: Terraform Init
      run: terraform init
      working-directory: ./Documents/TERRAFORM_PROJECT/PROJECT_4

    - name: Terraform Apply
      id: apply
      run: terraform apply -auto-approve
      working-directory: Documents/TERRAFORM_PROJECT/PROJECT_4
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        
    - name: Output Website URL
      run: |
          WEBSITE_URL=$(terraform output -raw website_url)
          echo "Website URL: $WEBSITE_URL"
      working-directory: Documents/TERRAFORM_PROJECT/PROJECT_4
